
spring.application.name=transIA
server.port=8182


spring.datasource.url=jdbc:postgresql://localhost:5432/Transia
spring.datasource.username=postgres
spring.datasource.password=Grace1234
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


springdoc.swagger-ui.path=/swagger-ui.html


jwt.jwtSecret=FinanceAppSecretKey2026SpringBootSecurityJWTMinimum256Bits!!!
jwt.jwtExpirationMs=86400000


server.error.include-message=always