spring.application.name=transIA
server.port=8182

# Inclure le profil local s'il est présent sur la machine
spring.profiles.include=local

# ====== Configuration JPA Commune ======
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ====== Configuration Swagger ======
springdoc.swagger-ui.path=/swagger-ui.html

# ====== JWT Configuration ======
jwt.jwtSecret=FinanceAppSecretKey2026SpringBootSecurityJWTMinimum256Bits!!!
jwt.jwtExpirationMs=86400000