spring.application.name=Transia

server.port=8181

spring.datasource.url=jdbc:postgresql://localhost:5432/Transia
spring.datasource.username=postgres
spring.datasource.password=Grace1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true


# ====Configuration swagger===========
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# JWT CONFIGURATION
# ===============================
jwt.jwtSecret=FinanceAppSecretKey2026SpringBootSecurityJWTMinimum256Bits!!!
jwt.jwtExpirationMs=3600000